name: Trigger auto deployment for container-app-urj6iw6fczowq

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'result/**'
    - '.github/workflows/container-app-urj6iw6fczowq-AutoDeployTrigger-90baaaaf-31e7-4821-bdf7-1188fc6fb7d7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPURJ6IW6FCZOWQ_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPURJ6IW6FCZOWQ_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPURJ6IW6FCZOWQ_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/result 
          registryUrl: containerregistryurj6iw6fczowq.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPURJ6IW6FCZOWQ_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPURJ6IW6FCZOWQ_REGISTRY_PASSWORD }}
          containerAppName: container-app-urj6iw6fczowq
          resourceGroup: examplevotingappa54d
          imageToBuild: containerregistryurj6iw6fczowq.azurecr.io/container-app-urj6iw6fczowq:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


