name: Trigger auto deployment for container-app-uurxr6fbzoj6w

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'result/**'
    - '.github/workflows/container-app-uurxr6fbzoj6w-AutoDeployTrigger-12e4ea72-e2d2-4de6-8196-0b12ca664f02.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPUURXR6FBZOJ6W_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPUURXR6FBZOJ6W_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPUURXR6FBZOJ6W_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/result 
          registryUrl: containerregistryuurxr6fbzoj6w.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPUURXR6FBZOJ6W_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPUURXR6FBZOJ6W_REGISTRY_PASSWORD }}
          containerAppName: container-app-uurxr6fbzoj6w
          resourceGroup: examplevotingappb0f6
          imageToBuild: containerregistryuurxr6fbzoj6w.azurecr.io/container-app-uurxr6fbzoj6w:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


