name: Trigger auto deployment for container-app-gzh4nptlqwufw

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'result/**'
    - '.github/workflows/container-app-gzh4nptlqwufw-AutoDeployTrigger-7967c074-2724-4ce9-84dc-23b8fe366bf5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPGZH4NPTLQWUFW_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPGZH4NPTLQWUFW_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPGZH4NPTLQWUFW_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/result 
          registryUrl: containerregistrygzh4nptlqwufw.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPGZH4NPTLQWUFW_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPGZH4NPTLQWUFW_REGISTRY_PASSWORD }}
          containerAppName: container-app-gzh4nptlqwufw
          resourceGroup: examplevotingapp927f
          imageToBuild: containerregistrygzh4nptlqwufw.azurecr.io/container-app-gzh4nptlqwufw:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


